name: nawel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  firebase_auth: ^5.6.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: dm_sans
      fonts:
        - asset: assets/fonts/dm_sans/DM_Sans-Regular.ttf
        - asset: assets/fonts/dm_sans/DM_Sans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DM_Sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DM_Sans-Italic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-Light.ttf
          weight: 300
        - asset: assets/fonts/dm_sans/DM_Sans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-Black.ttf
          weight: 900
        - asset: assets/fonts/dm_sans/DM_Sans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/dm_sans/DM_Sans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DM_Sans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/dm_sans/DM_Sans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/dm_sans/DM_Sans-Thin.ttf
          weight: 100
        - asset: assets/fonts/dm_sans/DM_Sans-ThinItalic.ttf
          weight: 100
          style: italic