name: nawel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  cloud_firestore: ^5.6.9
  dartz: ^0.10.1
  dio: ^5.8.0+1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.5
  quickalert: ^1.1.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: dm_sans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Light.ttf
          weight: 300
        - asset: assets/fonts/dm_sans/DMSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Black.ttf
          weight: 900
        - asset: assets/fonts/dm_sans/DMSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/dm_sans/DMSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/dm_sans/DMSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/dm_sans/DMSans-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/dm_sans/DMSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/dm_sans/DMSans-ThinItalic.ttf
          weight: 100
          style: italic
