// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu-xzDQaXPaJXj_IMK75y9mQGayVmJ-gw',
    appId: '1:566322638227:web:0fd287c0f12733ca1b8c66',
    messagingSenderId: '566322638227',
    projectId: 'nawel-8208c',
    authDomain: 'nawel-8208c.firebaseapp.com',
    storageBucket: 'nawel-8208c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFrhoqUCugmNeXezs4g6ezoxhSpoqafg',
    appId: '1:566322638227:android:dcca5abf3d11627c1b8c66',
    messagingSenderId: '566322638227',
    projectId: 'nawel-8208c',
    storageBucket: 'nawel-8208c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUhGYx1lTTUvOmJDi4hNA_dhkPCzwWCWM',
    appId: '1:566322638227:ios:d3930e06889739bf1b8c66',
    messagingSenderId: '566322638227',
    projectId: 'nawel-8208c',
    storageBucket: 'nawel-8208c.firebasestorage.app',
    iosBundleId: 'com.example.nawel',
  );
}
